spring.application.name=Journal App

spring.data.mongodb.uri = mongodb+srv://cluster:cluster12345@cluster0.kcdxtpw.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#spring.data.mongodb.database = journaldb
#spring.data.mongodb.username = myuser
#spring.data.mongodb.password = mypassword
spring.data.mongodb.auto-index-creation = true